### ISSUE TITLE
Save Execution Returns

### ISSUE THREAD

**Issue by lucaslimafernandes** [lucaslimafernandes/accio#1]
Save the execution results in local files or in a database. Each execution can have an associated log, containing:
- [ ] Command executed.
- [ ] Standard return (stdout) and standard error (stderr).
- [ ] Exit code.
- [ ] Execution timestamp.
- [ ] Node where it was executed.
- [ ] Value: Facilitates auditing and future reuse, as in the case of Docker Swarm.

**Comment by lucaslimafernandes** [comment]
Runfile example:

```yaml
tasks:
  - name: init_swarm
    node: 
      - master
    command: 
      docker swarm init | grep "token" | awk '{print $5}'
    save_output_as: swarm_token
```
