### ISSUE TITLE
Reuse Execution Returns

### ISSUE THREAD

**Issue by lucaslimafernandes** [lucaslimafernandes/accio#2]
Allow the use of placeholders for values ​​returned from commands. 

Example:

- After running docker swarm init, capture the join token and automatically reuse it in other runs.

Implementation: Use dynamic variables in the runfile, which can be filled with return values ​​from previous runs.

Runfile example:
```yaml
tasks:
  - name: init_swarm
    node: 
      - master
    command: 
      docker swarm init | grep "token" | awk '{print $5}'
    save_output_as: swarm_token

  - name: join_swarm
    node: 
      - worker1
      - worker2
    command: 
      docker swarm join --token $swarm_token master_ip:2377

```

Depends on: [Save Execution Returns](https://github.com/lucaslimafernandes/accio/issues/1)
